### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by enannos** [Zimbra-Community/mailing-lists#8]
Hello,

I have installed the plugin which I find one of the most useful for Zimbra.
I am receiving the following errors(in the admin account mail) when I try to subscribe or unsubscribe:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/DataHandler
        at tk.barrydegraaff.processor.Main.main(Main.java:84)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more

Actually, when a user subscribes or unsubscribes, nothing happens.
The user is not receiving any email.

When I go to the admin area of the server (Tools and Migration->Mailing list) and click to approve the user, I receive the following error.

Zimbra Version: 8.8.15
What could it be the error here?

**Comment by ghost** [comment]
can you please change `java` 
to `/opt/zimbra/common/bin/java` in `/usr/local/sbin/process_mailinglists`

(https://github.com/Zimbra-Community/mailing-lists/blob/master/bin/process_mailinglists#L20)

And let me know if that fixes the issue, thanks!

**Comment by linehammer** [comment]
As the name suggests this exception in Java occurs when JVM  tries to load a particular class and doesn't found the requested class in the classpath you specified. This means that, your classpath is broken.  Java ClassNotFoundException thrown when an application tries to load in a class through its string name using:

- The forName method in class Class.
- The findSystemClass method in class ClassLoader .
- The loadClass method in class ClassLoader.

When you get a [ClassNotFoundException](http://net-informations.com/java/cjava/notfound.htm) , it means that the Java Virtual Machine has traversed the entire classpath you specified and not found the class you've attempted to reference. The one and only solution is to check your classpath carefully.

Verify the name of the requested class is correct and the specified .jar file exists in your classpath. If not, you must explicitly add it to your application’s classpath.

If it's present in your classpath then there is high chance that your classpath is getting overridden or application is using classpath specified in jar file or start-up script and to fix that you need to find the exact classpath used by your application.

**Comment by ghost** [comment]
yes, that is why I pointed out to use the Java shipped by Zimbra, that 
should have all in the classpath, try and run as use Zimbra as well.
